export default {
  translation: {
    home_screen: {
      title: 'Home',
      banner: {
        upcoming_lesson: 'Upcoming lesson',
        no_upcoming_lesson: 'No upcoming lesson',
        total_study_time: 'Total study time',
        join_lesson: 'Join lesson',
      },
      recommended_tutors: 'Recommended tutors',
      see_all: 'See all',
    },
    navigator: {
      home: 'Home',
      tutor: 'Tutor',
      schedule: 'Schedule',
      message: 'Message',
      course: 'Course',
    },
    tutor_screen: {
      title: 'Tutor',
      search_placeholder: 'Search for tutor',
      total: 'Total',
      tutors: 'tutors',
      reset: 'Reset',
      of: 'of',
      filter: {
        title: 'Filter',
        specialty: 'Specialty',
        nationality: 'Nationality',
        apply: 'Apply',
        reset: 'Reset',
        foreigner: 'Foreigner',
        vietnamese: 'Vietnamese',
        native: 'Native English speaker',
      },
    },
    schedule_screen: {
      title: 'Schedule',
      description:
        'Below is the list of lessons you have booked. You can track when the lesson starts.',
      modal: {
        edit_note: 'Do you want to cancel this lesson?',
        cancel: 'Cancel lesson',
        back: 'Back',
      },
    },
    schedule_card: {
      note: 'Note',
      no_note: 'No note',
      cancel: 'Cancel lesson',
      join: 'Join lesson',
    },
    chat_screen: {
      title: 'GPT Assistant',
      placeholder: 'Type a message',
      init_message: 'Hello, I am GPT Assistant. How can I help you?',
    },
    course_screen: {
      title: 'Course',
      total: 'Total',
      course: 'courses',
      reset: 'Reset',
      of: 'of',
      placeholder: 'Search for course',
      filter: {
        title: 'Filter',
        category: 'Category',
        level: 'Level',
        reset: 'Reset',
        apply: 'Apply',
      },
    },
    course_card: {
      topics: 'Topics',
    },
    setting_screen: {
      title: 'Settings',
      booking_history: 'Booking history',
      advanced_setting: 'Advanced setting',
      our_website: 'Our website',
      logout: 'Log out',
    },
    history_screen: {
      title: 'Booking history',
      description:
        'This is the list of previous lessons. You can view feedback from your tutor and write a review.',
    },
    history_card: {
      review: 'Review',
      tutor_review: 'Tutor review',
      no_review: 'No review yet',
      note: 'Note',
      no_note: 'No note',
    },
    advanced_screen: {
      title: 'Advanced setting',
      language: 'Language',
      display: 'Display',
      dark: 'Dark theme',
    },
    tutor_detail_screen: {
      book_tutor: 'Book tutor',
      message: 'Message',
      review: 'View review',
      report: 'Report',
      experience: 'Experience',
      specialties: 'Specialties',
      education: 'Education',
      courses: 'Recommended courses',
      review_modal: {
        title: 'Review',
        total: 'Total',
        back: 'Close',
      },
      report_modal: {
        title: 'Report',
        description: 'Tell us what is wrong with this tutor',
        cancel: 'Cancel',
        submit: 'Submit',
      },
    },
  },
};
